import { ConflictException, Injectable } from '@nestjs/common';
import { DatabaseError } from 'pg';
import { DatabaseService, TransactionContext } from '../database/database.service';
import { CreateServiceDto } from './dto/create-service.dto';
import { CreateStageDto } from './dto/create-stage.dto';
import { UpdateServiceDto } from './dto/update-service.dto';
import { UpdateStageDto } from './dto/update-stage.dto';

@Injectable()
export class CatalogService {
  constructor(private readonly database: DatabaseService) {}
  private changed<T>(rows:T[]):T { if(!rows[0]) throw new ConflictException('Registro alterado por outro usuário; atualize a tela'); return rows[0]; }
  private duplicate(error:unknown,message:string):never { if(error instanceof DatabaseError&&error.code==='23505') throw new ConflictException(message); throw error; }

  listStages(context:TransactionContext) { return this.database.withContext(context,async client=>(await this.database.query(client,`select id,code,name,description,parent_stage_id as "parentStageId",display_order as "displayOrder",status,version from app.stage_catalog where organization_id=$1 order by display_order,name`,[context.organizationId])).rows); }
  async createStage(context:TransactionContext,input:CreateStageDto) { try { return await this.database.withContext(context,async client=>{ await this.database.query(client,`select pg_advisory_xact_lock(hashtextextended($1::text || ':stage-code',0))`,[context.organizationId]); return (await this.database.query(client,`insert into app.stage_catalog(organization_id,code,name,description,parent_stage_id,display_order,created_by,updated_by) select $1,'ET-'||lpad((coalesce(max(substring(code from '[0-9]+$')::int),0)+1)::text,2,'0'),$2,$3,$4,$5,$6,$6 from app.stage_catalog where organization_id=$1 returning id,code,name,description,parent_stage_id as "parentStageId",display_order as "displayOrder",status,version`,[context.organizationId,input.name,input.description??null,input.parentStageId??null,input.displayOrder,context.userId])).rows[0]; }); } catch(error) { return this.duplicate(error,'Não foi possível gerar o código da etapa'); } }
  updateStage(context:TransactionContext,id:string,input:UpdateStageDto) { return this.database.withContext(context,async client=>this.changed((await this.database.query(client,`update app.stage_catalog set name=coalesce($3,name),description=coalesce($4,description),parent_stage_id=coalesce($5,parent_stage_id),display_order=coalesce($6,display_order),status=coalesce($7,status),updated_by=$8 where organization_id=$1 and id=$2 and version=$9 returning id,code,name,description,parent_stage_id as "parentStageId",display_order as "displayOrder",status,version`,[context.organizationId,id,input.name??null,input.description??null,input.parentStageId??null,input.displayOrder??null,input.status??null,context.userId,input.version])).rows)); }
  deactivateStage(context:TransactionContext,id:string,version:number) { return this.database.withContext(context,async client=>this.changed((await this.database.query(client,`update app.stage_catalog set status='inactive',updated_by=$3 where organization_id=$1 and id=$2 and version=$4 returning id,code,name,status,version`,[context.organizationId,id,context.userId,version])).rows)); }

  listServices(context:TransactionContext) { return this.database.withContext(context,async client=>(await this.database.query(client,`select s.id,s.stage_id as "stageId",st.name as "stageName",s.code,s.name,s.description,s.unit_code as "unitCode",s.cost_category_code as "costCategoryCode",s.default_weight as "defaultWeight",s.default_duration_days as "defaultDurationDays",s.progress_criterion as "progressCriterion",s.status,s.version from app.service_catalog s join app.stage_catalog st on st.organization_id=s.organization_id and st.id=s.stage_id where s.organization_id=$1 order by s.name`,[context.organizationId])).rows); }
  async createService(context:TransactionContext,input:CreateServiceDto) { try { return await this.database.withContext(context,async client=>{ await this.database.query(client,`select pg_advisory_xact_lock(hashtextextended($1::text || ':service-code',0))`,[context.organizationId]); return (await this.database.query(client,`insert into app.service_catalog(organization_id,stage_id,code,name,description,unit_code,cost_category_code,default_weight,default_duration_days,progress_criterion,created_by,updated_by) select $1,$2,'SR-'||lpad((coalesce(max(substring(code from '[0-9]+$')::int),0)+1)::text,2,'0'),$3,$4,$5,$6,$7::numeric,$8,$9,$10,$10 from app.service_catalog where organization_id=$1 returning id,stage_id as "stageId",code,name,description,unit_code as "unitCode",cost_category_code as "costCategoryCode",default_weight as "defaultWeight",default_duration_days as "defaultDurationDays",progress_criterion as "progressCriterion",status,version`,[context.organizationId,input.stageId,input.name,input.description??null,input.unitCode,input.costCategoryCode,input.defaultWeight,input.defaultDurationDays,input.progressCriterion,context.userId])).rows[0]; }); } catch(error) { return this.duplicate(error,'Não foi possível gerar o código do serviço'); } }
  updateService(context:TransactionContext,id:string,input:UpdateServiceDto) { return this.database.withContext(context,async client=>this.changed((await this.database.query(client,`update app.service_catalog set stage_id=coalesce($3,stage_id),name=coalesce($4,name),description=coalesce($5,description),unit_code=coalesce($6,unit_code),cost_category_code=coalesce($7,cost_category_code),default_weight=coalesce($8::numeric,default_weight),default_duration_days=coalesce($9,default_duration_days),progress_criterion=coalesce($10,progress_criterion),status=coalesce($11,status),updated_by=$12 where organization_id=$1 and id=$2 and version=$13 returning id,stage_id as "stageId",code,name,description,unit_code as "unitCode",cost_category_code as "costCategoryCode",default_weight as "defaultWeight",default_duration_days as "defaultDurationDays",progress_criterion as "progressCriterion",status,version`,[context.organizationId,id,input.stageId??null,input.name??null,input.description??null,input.unitCode??null,input.costCategoryCode??null,input.defaultWeight??null,input.defaultDurationDays??null,input.progressCriterion??null,input.status??null,context.userId,input.version])).rows)); }
  deactivateService(context:TransactionContext,id:string,version:number) { return this.database.withContext(context,async client=>this.changed((await this.database.query(client,`update app.service_catalog set status='inactive',updated_by=$3 where organization_id=$1 and id=$2 and version=$4 returning id,code,name,status,version`,[context.organizationId,id,context.userId,version])).rows)); }
}
