import { ConflictException, Injectable } from '@nestjs/common';
import { DatabaseError } from 'pg';
import { DatabaseService, TransactionContext } from '../database/database.service';
import { CreateSupplierDto } from './dto/create-supplier.dto';
import { UpdateSupplierDto } from './dto/update-supplier.dto';

@Injectable()
export class SuppliersService {
  constructor(private readonly database:DatabaseService){}
  private changed<T>(rows:T[]):T{if(!rows[0])throw new ConflictException('Fornecedor alterado por outro usuário; atualize a tela');return rows[0];}
  private duplicate(error:unknown):never{if(error instanceof DatabaseError&&error.code==='23505')throw new ConflictException('CPF/CNPJ já cadastrado nesta organização');throw error;}
  list(context:TransactionContext){return this.database.withContext(context,async client=>(await this.database.query(client,`select id,person_type as "personType",legal_name as "legalName",trade_name as "tradeName",tax_id as "taxId",primary_specialty as "primarySpecialty",email,phone,average_lead_time_days as "averageLeadTimeDays",notes,status,version from app.suppliers where organization_id=$1 order by legal_name`,[context.organizationId])).rows);}
  async create(context:TransactionContext,input:CreateSupplierDto){try{return await this.database.withContext(context,async client=>(await this.database.query(client,`insert into app.suppliers(organization_id,person_type,legal_name,trade_name,tax_id,primary_specialty,email,phone,average_lead_time_days,notes,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) returning id,person_type as "personType",legal_name as "legalName",trade_name as "tradeName",tax_id as "taxId",primary_specialty as "primarySpecialty",email,phone,average_lead_time_days as "averageLeadTimeDays",notes,status,version`,[context.organizationId,input.personType,input.legalName,input.tradeName??null,input.taxId,input.primarySpecialty,input.email,input.phone,input.averageLeadTimeDays,input.notes??null,context.userId])).rows[0]);}catch(error){return this.duplicate(error);}}
  async update(context:TransactionContext,id:string,input:UpdateSupplierDto){try{return await this.database.withContext(context,async client=>this.changed((await this.database.query(client,`update app.suppliers set person_type=coalesce($3,person_type),legal_name=coalesce($4,legal_name),trade_name=coalesce($5,trade_name),tax_id=coalesce($6,tax_id),primary_specialty=coalesce($7,primary_specialty),email=coalesce($8,email),phone=coalesce($9,phone),average_lead_time_days=coalesce($10,average_lead_time_days),notes=coalesce($11,notes),status=coalesce($12,status),updated_by=$13 where organization_id=$1 and id=$2 and version=$14 returning id,person_type as "personType",legal_name as "legalName",trade_name as "tradeName",tax_id as "taxId",primary_specialty as "primarySpecialty",email,phone,average_lead_time_days as "averageLeadTimeDays",notes,status,version`,[context.organizationId,id,input.personType??null,input.legalName??null,input.tradeName??null,input.taxId??null,input.primarySpecialty??null,input.email??null,input.phone??null,input.averageLeadTimeDays??null,input.notes??null,input.status??null,context.userId,input.version])).rows));}catch(error){return this.duplicate(error);}}
  deactivate(context:TransactionContext,id:string,version:number){return this.database.withContext(context,async client=>this.changed((await this.database.query(client,`update app.suppliers set status='inactive',updated_by=$3 where organization_id=$1 and id=$2 and version=$4 returning id,legal_name as "legalName",status,version`,[context.organizationId,id,context.userId,version])).rows));}
}
