"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Eye, EyeOff, HardHat, LockKeyhole, LogIn } from "lucide-react";
import { api } from "@/lib/api";
import { BomzeikaApp } from "./bomzeika-app";

export type SessionUser={id:string;name:string;email:string;role:string};
type Session={user:SessionUser;organization:{id:string;name:string}};

export function AuthGate(){const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true);const check=useCallback(()=>api<Session>("/auth/me").then(setSession).catch(()=>setSession(null)).finally(()=>setLoading(false)),[]);useEffect(()=>{void check();const expired=()=>setSession(null);window.addEventListener("bomzeika:session-expired",expired);return()=>window.removeEventListener("bomzeika:session-expired",expired)},[check]);const logout=async()=>{await api("/auth/logout",{method:"POST"}).catch(()=>undefined);setSession(null)};if(loading)return <div className="auth-loading"><HardHat/><span>Carregando sessão segura…</span></div>;return session?<BomzeikaApp user={session.user} organizationName={session.organization.name} onLogout={logout}/>:<LoginScreen onSuccess={setSession}/>}

function LoginScreen({onSuccess}:{onSuccess:(session:Session)=>void}){const [show,setShow]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const form=new FormData(e.currentTarget);try{await api("/auth/login",{method:"POST",body:JSON.stringify({email:String(form.get("email")),password:String(form.get("password"))})},false);onSuccess(await api<Session>("/auth/me"))}catch(x){setError((x as Error).message)}finally{setSaving(false)}};return <main className="login-page"><section className="login-brand"><div className="login-logo"><HardHat/><div><strong>BOMzeika</strong><span>OBRAS</span></div></div><div><span>GESTÃO DE ALTO PADRÃO</span><h1>Sua obra sob controle, do primeiro projeto à entrega.</h1><p>Planejamento, custos, contratos, execução e decisões reunidos com segurança em um único ambiente.</p></div><small>Ambiente protegido · Acesso restrito</small></section><section className="login-panel"><form className="login-card" onSubmit={submit}><div className="login-icon"><LockKeyhole/></div><span className="login-eyebrow">Acesso ao sistema</span><h2>Entre na sua conta</h2><p>Use as credenciais cadastradas para acessar suas obras.</p><label>E-mail<input name="email" type="email" autoComplete="username" required placeholder="seu@email.com"/></label><label>Senha<div className="password-field"><input name="password" type={show?"text":"password"} autoComplete="current-password" minLength={12} maxLength={128} required placeholder="Digite sua senha"/><button type="button" aria-label={show?"Ocultar senha":"Mostrar senha"} onClick={()=>setShow(x=>!x)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="login-error" role="alert">{error}</div>}<button className="login-submit" disabled={saving}>{saving?"Verificando…":<><LogIn/> Entrar com segurança</>}</button><small>Problemas de acesso? Procure o administrador do sistema.</small></form></section></main>}
