"use client";

import { CalendarDays, ChevronDown, ChevronRight, MoreHorizontal, Plus, Search, Settings2, Trash2 } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { BannerProject } from "./project-banner";

type Scale="day"|"week"|"month"|"semester"|"year";
type ViewMode="gantt"|"list";
type Supplier={id:string;legalName:string;tradeName?:string;status:string};
type ScheduleItem={id:string;source:"configured"|"configured_service"|"manual";code?:string;name:string;itemType?:"stage"|"substage"|"service"|"manual";groupName?:string;substageName?:string;supplierId?:string;supplierName?:string;plannedStart:string;plannedEnd:string;progressPercentage:string;status:string;notes?:string;version:number|string};
const statuses:Record<string,string>={planned:"Planejada",released:"Liberada",blocked:"Bloqueada",in_progress:"Em execução",completed:"Concluída",suspended:"Suspensa",cancelled:"Cancelada"};
const scales:Record<Scale,string>={day:"Dia",week:"Semana",month:"Mês",semester:"Semestre",year:"Ano"};
const utc=(value:string)=>new Date(`${value.slice(0,10)}T00:00:00Z`);
const iso=(date:Date)=>date.toISOString().slice(0,10);
const dateBr=(value:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",year:"2-digit",timeZone:"UTC"}).format(utc(value));
const add=(date:Date,scale:Scale)=>{const next=new Date(date);if(scale==="day")next.setUTCDate(next.getUTCDate()+1);if(scale==="week")next.setUTCDate(next.getUTCDate()+7);if(scale==="month")next.setUTCMonth(next.getUTCMonth()+1);if(scale==="semester")next.setUTCMonth(next.getUTCMonth()+6);if(scale==="year")next.setUTCFullYear(next.getUTCFullYear()+1);return next};
function floorDate(date:Date,scale:Scale){const value=new Date(date);if(scale==="week")value.setUTCDate(value.getUTCDate()-((value.getUTCDay()+6)%7));else if(scale!=="day"){value.setUTCDate(1);value.setUTCMonth(scale==="semester"?(value.getUTCMonth()<6?0:6):scale==="year"?0:value.getUTCMonth())}return value}
function bucketLabel(date:Date,scale:Scale){if(scale==="day")return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",timeZone:"UTC"}).format(date);if(scale==="week")return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",timeZone:"UTC"}).format(date);if(scale==="semester")return`${date.getUTCMonth()<6?1:2}º sem. ${date.getUTCFullYear()}`;if(scale==="year")return String(date.getUTCFullYear());return new Intl.DateTimeFormat("pt-BR",{month:"short",year:"numeric",timeZone:"UTC"}).format(date)}

export function ScheduleWorkspace({onConfigure}:{onConfigure:()=>void}){
 const [projects,setProjects]=useState<BannerProject[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[projectId,setProjectId]=useState(""),[items,setItems]=useState<ScheduleItem[]>([]);
 const [scale,setScale]=useState<Scale>("week"),[viewMode,setViewMode]=useState<ViewMode>("gantt"),[query,setQuery]=useState(""),[supplierFilter,setSupplierFilter]=useState(""),[statusFilter,setStatusFilter]=useState(""),[collapsed,setCollapsed]=useState<Set<string>>(new Set());
 const [open,setOpen]=useState(false),[edit,setEdit]=useState<ScheduleItem|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const task=setTimeout(()=>void Promise.all([api<BannerProject[]>("/projects"),api<Supplier[]>("/suppliers")]).then(([projectRows,supplierRows])=>{const available=projectRows.filter(x=>x.status!=="cancelled");setProjects(available);setSuppliers(supplierRows.filter(x=>x.status==="active"));setProjectId(current=>available.some(x=>x.id===current)?current:(available[0]?.id??""))}).catch(e=>setError((e as Error).message)),0);return()=>clearTimeout(task)},[]);
 const load=useCallback(async()=>{if(!projectId){setItems([]);return}try{setItems(await api<ScheduleItem[]>(`/projects/${projectId}/schedule`));setError("")}catch(e){setError((e as Error).message)}},[projectId]);
 useEffect(()=>{const task=setTimeout(()=>void load(),0);return()=>clearTimeout(task)},[load]);
 const filtered=useMemo(()=>items.filter(item=>(!query||`${item.code??""} ${item.name}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")))&&(!supplierFilter||item.supplierId===supplierFilter)&&(!statusFilter||item.status===statusFilter)),[items,query,supplierFilter,statusFilter]);
 const groups=useMemo(()=>{const map=new Map<string,ScheduleItem[]>();for(const item of filtered){const key=item.groupName||"Etapas da obra";map.set(key,[...(map.get(key)??[]),item])}return [...map.entries()]},[filtered]);
 const visible=useMemo(()=>groups.flatMap(([name,rows])=>collapsed.has(name)?[]:rows),[groups,collapsed]);
 const range=useMemo(()=>{const today=new Date(),starts=filtered.map(x=>utc(x.plannedStart).getTime()),ends=filtered.map(x=>utc(x.plannedEnd).getTime()),start=floorDate(new Date(Math.min(...(starts.length?starts:[today.getTime()]))),scale),last=new Date(Math.max(...(ends.length?ends:[add(today,"month").getTime()]))),buckets:Date[]=[];for(let cursor=start;cursor<=last||buckets.length<2;cursor=add(cursor,scale)){buckets.push(cursor);if(buckets.length>180)break}const end=add(buckets.at(-1)!,scale),days=Math.max(1,(end.getTime()-start.getTime())/86400000);return{start,end,days,buckets}},[filtered,scale]);
 const todayPosition=(Date.now()-range.start.getTime())/86400000/range.days*100;
 const clearFilters=()=>{setQuery("");setSupplierFilter("");setStatusFilter("")};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError("");const form=new FormData(e.currentTarget),body={name:String(form.get("name")),supplierId:String(form.get("supplierId")),plannedStart:String(form.get("plannedStart")),plannedEnd:String(form.get("plannedEnd")),status:String(form.get("status")),progressPercentage:Number(form.get("progressPercentage")||0),notes:String(form.get("notes")||"")||undefined,...(edit?{version:Number(edit.version)}:{})};try{await api(`/projects/${projectId}/schedule${edit?`/${edit.source}/${edit.id}`:""}`,{method:edit?"PATCH":"POST",body:JSON.stringify(body)});setOpen(false);setEdit(null);await load()}catch(x){setError((x as Error).message)}finally{setSaving(false)}};
 const remove=async(item:ScheduleItem)=>{if(item.source!=="manual"||!confirm(`Excluir a atividade “${item.name}”?`))return;try{await api(`/projects/${projectId}/schedule/manual/${item.id}?version=${item.version}`,{method:"DELETE"});setOpen(false);setEdit(null);await load()}catch(e){setError((e as Error).message)}};
 const openEditor=(item:ScheduleItem|null)=>{setEdit(item);setOpen(true)};
 return <div className="schedule-page">
  <header className="schedule-head"><div><h1>Cronograma</h1><p>Etapas e serviços da obra em uma visão integrada.</p></div><select aria-label="Obra do cronograma" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Selecione uma obra</option>{projects.map(x=><option key={x.id} value={x.id}>{x.name}{x.address?` · ${x.address}`:""}</option>)}</select><div className="schedule-head-actions"><button className="secondary-button" onClick={onConfigure}><Settings2 size={16}/> Configurar etapas</button><button className="primary-button" onClick={()=>openEditor(null)} disabled={!projectId}><Plus size={17}/> Incluir item</button></div></header>
  {error&&<p className="form-error">{error}</p>}
  {projectId&&<>
   <section className="schedule-filters" aria-label="Filtros do cronograma"><label className="schedule-search"><Search size={17}/><input aria-label="Buscar etapa ou serviço" placeholder="Buscar etapa ou serviço..." value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Fornecedor<select value={supplierFilter} onChange={e=>setSupplierFilter(e.target.value)}><option value="">Todos</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.tradeName||x.legalName}</option>)}</select></label><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos</option>{Object.entries(statuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="filter-clear" onClick={clearFilters}>Limpar filtros</button></section>
   <section className="schedule-controls"><div className="schedule-segment"><button className={viewMode==="gantt"?"active":""} onClick={()=>setViewMode("gantt")}>Gantt</button><button className={viewMode==="list"?"active":""} onClick={()=>setViewMode("list")}>Lista</button></div>{viewMode==="gantt"&&<div className="schedule-scale"><span>Escala:</span>{Object.entries(scales).map(([value,label])=><button key={value} className={scale===value?"active":""} onClick={()=>setScale(value as Scale)}>{label}</button>)}</div>}<button className="collapse-all" onClick={()=>setCollapsed(collapsed.size?new Set():new Set(groups.map(([name])=>name)))}>{collapsed.size?"Expandir etapas":"Recolher etapas"}</button></section>
   <section className={`schedule-board ${viewMode==="list"?"list-view":""}`} style={{"--gantt-width":`${Math.max(760,range.buckets.length*(scale==="day"?44:scale==="week"?92:120))}px`} as React.CSSProperties}>
    <div className="schedule-grid schedule-grid-head"><div className="schedule-info-head"><span>Etapa / serviço</span><span>Fornecedor</span><span>Início</span><span>Término</span><span>Status</span><span/></div>{viewMode==="gantt"&&<div className="schedule-timeline-head">{range.buckets.map(bucket=><span key={iso(bucket)}>{bucketLabel(bucket,scale)}</span>)}</div>}</div>
    {groups.map(([groupName,rows])=><ScheduleHierarchyGroup key={groupName} groupName={groupName} rows={rows} collapsed={collapsed.has(groupName)} range={range} viewMode={viewMode} todayPosition={todayPosition} onToggle={()=>setCollapsed(current=>{const next=new Set(current);next.has(groupName)?next.delete(groupName):next.add(groupName);return next})} onEdit={openEditor}/>)}
    {!visible.length&&<div className="state-box">Nenhum item corresponde aos filtros selecionados.</div>}
   </section>
   <footer className="schedule-legend"><span><i className="planned"/>Planejada</span><span><i className="in_progress"/>Em execução</span><span><i className="completed"/>Concluída</span><span><i className="suspended"/>Suspensa</span><span><i className="blocked"/>Bloqueada</span><small>Clique em um item para editar datas, fornecedor, status e avanço.</small></footer>
  </>}
  {open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="modal schedule-modal" role="dialog" aria-modal="true"><header><div><h2>{edit?"Editar item":"Incluir item"}</h2>{edit&&<p>{edit.code&&`${edit.code} · `}{edit.name}</p>}</div><button className="icon-button" onClick={()=>setOpen(false)}>×</button></header><form className="entity-form" onSubmit={submit}><div className="form-grid"><label className="full">Nome<input name="name" required minLength={3} maxLength={180} readOnly={edit?.source==="configured"} defaultValue={edit?.name}/></label><label>Fornecedor<select name="supplierId" required defaultValue={edit?.supplierId??""}><option value="">Selecione</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.tradeName||x.legalName}</option>)}</select></label><label>Status<select name="status" defaultValue={edit?.status??"planned"}>{Object.entries(statuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Início<input name="plannedStart" type="date" required defaultValue={edit?.plannedStart?.slice(0,10)}/></label><label>Término<input name="plannedEnd" type="date" required defaultValue={edit?.plannedEnd?.slice(0,10)}/></label><label>Avanço (%)<input name="progressPercentage" type="number" min="0" max="100" step="0.01" defaultValue={edit?.progressPercentage??0}/></label><label className="full">Observações<textarea name="notes" maxLength={2000} defaultValue={edit?.notes}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="form-actions">{edit?.source==="manual"&&<button type="button" className="schedule-delete" onClick={()=>void remove(edit)}><Trash2 size={16}/> Excluir item</button>}<button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?"Salvando…":"Salvar alterações"}</button></div></form></section></div>}
 </div>;
}

function ScheduleHierarchyGroup({groupName,rows,collapsed,range,viewMode,todayPosition,onToggle,onEdit}:{groupName:string;rows:ScheduleItem[];collapsed:boolean;range:{start:Date;days:number};viewMode:ViewMode;todayPosition:number;onToggle:()=>void;onEdit:(item:ScheduleItem)=>void}){
 const stages=rows.filter(x=>x.itemType==="stage"),substages=rows.filter(x=>x.itemType==="substage"),services=rows.filter(x=>x.itemType==="service"),manual=rows.filter(x=>x.itemType==="manual");
 const ordered:ScheduleItem[]=[...stages];for(const substage of substages){ordered.push(substage,...services.filter(service=>service.substageName===substage.name))}ordered.push(...services.filter(service=>!service.substageName),...manual);
 return <div className="schedule-group"><div className="schedule-grid schedule-group-row"><button className="schedule-group-name" onClick={onToggle}>{collapsed?<ChevronRight size={16}/>:<ChevronDown size={16}/>}<strong>{groupName}</strong><small>{substages.length} subetapa(s) · {services.length} serviço(s)</small></button>{viewMode==="gantt"&&<div className="schedule-group-line"><span style={{left:`${Math.max(0,Math.min(100,(Math.min(...rows.map(x=>utc(x.plannedStart).getTime()))-range.start.getTime())/86400000/range.days*100))}%`,width:`${Math.max(1,(Math.max(...rows.map(x=>utc(x.plannedEnd).getTime()))-Math.min(...rows.map(x=>utc(x.plannedStart).getTime()))+86400000)/86400000/range.days*100)}%`}}/></div>}</div>{!collapsed&&ordered.map(item=><ScheduleRow key={`${item.source}-${item.id}`} item={item} range={range} viewMode={viewMode} todayPosition={todayPosition} onEdit={()=>onEdit(item)}/>)}</div>
}

function ScheduleRow({item,range,viewMode,todayPosition,onEdit}:{item:ScheduleItem;range:{start:Date;days:number};viewMode:ViewMode;todayPosition:number;onEdit:()=>void}){const left=Math.max(0,(utc(item.plannedStart).getTime()-range.start.getTime())/86400000/range.days*100),width=Math.max(1,(utc(item.plannedEnd).getTime()-utc(item.plannedStart).getTime()+86400000)/86400000/range.days*100),progress=Math.round(Number(item.progressPercentage)),kind=item.source==="manual"?"Manual":item.itemType==="service"?"Serviço":item.itemType==="substage"?"Subetapa":"Etapa";return <button className={`schedule-grid schedule-item-row hierarchy-${item.itemType??"manual"}`} onClick={onEdit}><div className="schedule-item-info"><span><b>{item.code&&`${item.code} · `}{item.name}</b><small>{kind}</small></span><span>{item.supplierName||"—"}</span><span>{dateBr(item.plannedStart)}</span><span>{dateBr(item.plannedEnd)}</span><span><em className={`schedule-status ${item.status}`}>{statuses[item.status]??item.status}</em></span><span><MoreHorizontal size={17}/></span></div>{viewMode==="gantt"&&<div className="schedule-track">{todayPosition>0&&todayPosition<100&&<i className="today-line" style={{left:`${todayPosition}%`}}/>}<span className={`schedule-bar ${item.status}`} style={{left:`${left}%`,width:`${width}%`}}><i style={{width:`${progress}%`}}/>{width>5&&<b>{progress}%</b>}</span></div>}</button>}
