import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { DatabaseService, TransactionContext } from '../database/database.service';
import { DatabaseError } from 'pg';
import { CreateProjectDto } from './dto/create-project.dto';
import { UpdateProjectDto } from './dto/update-project.dto';

const selection=`p.id,p.name,p.address,p.condominium,p.built_area_m2 as "builtAreaM2",p.approved_budget as "approvedBudget",p.planned_start as "plannedStart",p.planned_end as "plannedEnd",p.technical_responsible_id as "technicalResponsibleId",p.status,p.version,(i.project_id is not null) as "hasMainImage",i.version as "mainImageVersion"`;
type UploadedImage={buffer:Buffer;mimetype:string;originalname:string;size:number};
@Injectable()
export class ProjectsService {
  constructor(private readonly database:DatabaseService){}
  private changed<T>(rows:T[]):T{if(!rows[0])throw new ConflictException('Obra alterada por outro usuário; atualize a tela');return rows[0];}
  list(context:TransactionContext){return this.database.withContext(context,async client=>(await this.database.query(client,`select ${selection} from app.projects p left join app.project_main_images i on i.organization_id=p.organization_id and i.project_id=p.id where p.organization_id=$1 and p.status<>'cancelled' order by p.created_at desc`,[context.organizationId])).rows);}
  get(context:TransactionContext,id:string){return this.database.withContext(context,async client=>{const result=await this.database.query(client,`select ${selection} from app.projects p left join app.project_main_images i on i.organization_id=p.organization_id and i.project_id=p.id where p.organization_id=$1 and p.id=$2`,[context.organizationId,id]);if(!result.rows[0])throw new NotFoundException('Obra não encontrada');return result.rows[0];});}
  async create(context:TransactionContext,input:CreateProjectDto){try{return await this.database.withContext(context,async client=>{const row=(await this.database.query<{id:string}>(client,`insert into app.projects(organization_id,name,address,condominium,built_area_m2,approved_budget,planned_start,planned_end,status,technical_responsible_id,created_by,updated_by) values($1,$2,$3,$4,$5::numeric,$6::numeric,$7::date,$8::date,$9,$10,$11,$11) returning id`,[context.organizationId,input.name,input.address,input.condominium??null,input.builtAreaM2,input.approvedBudget,input.plannedStart,input.plannedEnd,input.status,input.technicalResponsibleId??null,context.userId])).rows[0]!;return (await this.database.query(client,`select ${selection} from app.projects p left join app.project_main_images i on i.organization_id=p.organization_id and i.project_id=p.id where p.organization_id=$1 and p.id=$2`,[context.organizationId,row.id])).rows[0];});}catch(error){if(error instanceof DatabaseError&&error.code==='23505')throw new ConflictException('Já existe uma obra com o mesmo nome, endereço e condomínio');throw error;}}
  async update(context:TransactionContext,id:string,input:UpdateProjectDto){if(input.plannedStart&&input.plannedEnd&&input.plannedEnd<input.plannedStart)throw new ConflictException('Término deve ser posterior ao início');try{return await this.database.withContext(context,async client=>{this.changed((await this.database.query(client,`update app.projects set name=coalesce($3,name),address=coalesce($4,address),condominium=coalesce($5,condominium),built_area_m2=coalesce($6::numeric,built_area_m2),approved_budget=coalesce($7::numeric,approved_budget),planned_start=coalesce($8::date,planned_start),planned_end=coalesce($9::date,planned_end),status=coalesce($10,status),technical_responsible_id=coalesce($11,technical_responsible_id),updated_by=$12 where organization_id=$1 and id=$2 and version=$13 returning id`,[context.organizationId,id,input.name??null,input.address??null,input.condominium??null,input.builtAreaM2??null,input.approvedBudget??null,input.plannedStart??null,input.plannedEnd??null,input.status??null,input.technicalResponsibleId??null,context.userId,input.version])).rows);return (await this.database.query(client,`select ${selection} from app.projects p left join app.project_main_images i on i.organization_id=p.organization_id and i.project_id=p.id where p.organization_id=$1 and p.id=$2`,[context.organizationId,id])).rows[0];});}catch(error){if(error instanceof DatabaseError&&error.code==='23505')throw new ConflictException('Já existe uma obra com o mesmo nome, endereço e condomínio');throw error;}}
  cancel(context:TransactionContext,id:string,version:number){return this.database.withContext(context,async client=>{this.changed((await this.database.query(client,`update app.projects set status='cancelled',updated_by=$3 where organization_id=$1 and id=$2 and version=$4 returning id`,[context.organizationId,id,context.userId,version])).rows);return (await this.database.query(client,`select ${selection} from app.projects p left join app.project_main_images i on i.organization_id=p.organization_id and i.project_id=p.id where p.organization_id=$1 and p.id=$2`,[context.organizationId,id])).rows[0];});}
  saveMainImage(context:TransactionContext,id:string,file:UploadedImage|undefined){if(!file)throw new BadRequestException('Selecione uma imagem');if(!this.isValidImage(file))throw new BadRequestException('Use uma imagem JPEG, PNG ou WebP válida');return this.database.withContext(context,async client=>{const project=await this.database.query(client,'select id from app.projects where organization_id=$1 and id=$2',[context.organizationId,id]);if(!project.rows[0])throw new NotFoundException('Obra não encontrada');const row=(await this.database.query(client,`insert into app.project_main_images(organization_id,project_id,content,mime_type,file_name,size_bytes,uploaded_by) values($1,$2,$3,$4,$5,$6,$7) on conflict(organization_id,project_id) do update set content=excluded.content,mime_type=excluded.mime_type,file_name=excluded.file_name,size_bytes=excluded.size_bytes,uploaded_by=excluded.uploaded_by returning version,updated_at as "updatedAt"`,[context.organizationId,id,file.buffer,file.mimetype,file.originalname.slice(0,180),file.size,context.userId])).rows[0];await this.database.query(client,`insert into app.audit_events(organization_id,project_id,actor_user_id,action,entity_type,entity_id,request_id,changed_fields,new_snapshot) values($1,$2,$3,'upload','app.project_main_images',$2,$4,array['file_name','mime_type','size_bytes'],jsonb_build_object('file_name',$5::text,'mime_type',$6::text,'size_bytes',$7::integer))`,[context.organizationId,id,context.userId,context.requestId,file.originalname.slice(0,180),file.mimetype,file.size]);return{hasMainImage:true,...row};});}
  getMainImage(context:TransactionContext,id:string){return this.database.withContext(context,async client=>{const row=(await this.database.query<{content:Buffer;mimeType:string;fileName:string;size:number}>(client,`select content,mime_type as "mimeType",file_name as "fileName",size_bytes as size from app.project_main_images where organization_id=$1 and project_id=$2`,[context.organizationId,id])).rows[0];if(!row)throw new NotFoundException('Imagem principal não cadastrada');return row;});}
  removeMainImage(context:TransactionContext,id:string){return this.database.withContext(context,async client=>{const deleted=(await this.database.query<{fileName:string;mimeType:string;size:number}>(client,`delete from app.project_main_images where organization_id=$1 and project_id=$2 returning file_name as "fileName",mime_type as "mimeType",size_bytes as size`,[context.organizationId,id])).rows[0];if(!deleted)throw new NotFoundException('Imagem principal não cadastrada');await this.database.query(client,`insert into app.audit_events(organization_id,project_id,actor_user_id,action,entity_type,entity_id,request_id,changed_fields,previous_snapshot) values($1,$2,$3,'delete','app.project_main_images',$2,$4,array['file_name','mime_type','size_bytes'],jsonb_build_object('file_name',$5::text,'mime_type',$6::text,'size_bytes',$7::integer))`,[context.organizationId,id,context.userId,context.requestId,deleted.fileName,deleted.mimeType,deleted.size]);return{hasMainImage:false};});}
  private isValidImage(file:UploadedImage){const b=file.buffer;if(file.size<12||!['image/jpeg','image/png','image/webp'].includes(file.mimetype))return false;return(file.mimetype==='image/jpeg'&&b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)||(file.mimetype==='image/png'&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(file.mimetype==='image/webp'&&b.subarray(0,4).toString()==='RIFF'&&b.subarray(8,12).toString()==='WEBP');}
}
