import { BadRequestException, Injectable } from '@nestjs/common';
import { DatabaseService, TransactionContext } from '../database/database.service';
import { AssignStageDto } from './dto/assign-stage.dto';
import { AssignServiceDto } from './dto/assign-service.dto';
import { CreateDependencyDto } from './dto/create-dependency.dto';
import { AssignStageBatchDto } from './dto/assign-stage-batch.dto';

@Injectable()
export class ProjectConfigService {
  constructor(private readonly db: DatabaseService) {}

  list(context: TransactionContext, projectId: string) {
    return this.db.withContext(context, async (client) => ({
      stages: (await this.db.query(client, `select ps.id,ps.catalog_stage_id as "catalogStageId",sc.code,sc.name,sc.item_type as "itemType",sc.parent_stage_id as "parentStageId",ps.display_order as "displayOrder",ps.planned_start as "plannedStart",ps.planned_end as "plannedEnd",ps.physical_weight as "physicalWeight",ps.progress_percentage as "progressPercentage",ps.status from app.project_stages ps join app.stage_catalog sc on sc.organization_id=ps.organization_id and sc.id=ps.catalog_stage_id where ps.organization_id=$1 and ps.project_id=$2 order by ps.display_order`, [context.organizationId, projectId])).rows,
      dependencies: (await this.db.query(client, `select id,predecessor_stage_id as "predecessorStageId",successor_stage_id as "successorStageId",dependency_type as "dependencyType",lag_days as "lagDays",reason from app.project_stage_dependencies where organization_id=$1 and project_id=$2`, [context.organizationId, projectId])).rows,
    }));
  }

  addStages(context:TransactionContext,projectId:string,input:AssignStageBatchDto){if(input.plannedEnd<input.plannedStart)throw new BadRequestException('Término deve ser posterior ao início');const total=Number(input.totalPhysicalWeight);if(!Number.isFinite(total)||total<=0||total>100)throw new BadRequestException('O peso total deve ser maior que zero e menor ou igual a 100%');return this.db.withContext(context,async client=>{const unique=[...new Set(input.catalogStageIds)],weight=(total/unique.length).toFixed(4);const configuredWeight=Number((await this.db.query<{total:string}>(client,`select coalesce(sum(physical_weight),0)::text as total from app.project_stages where organization_id=$1 and project_id=$2`,[context.organizationId,projectId])).rows[0]?.total??0);if(configuredWeight+total>100.0001)throw new BadRequestException('A soma dos pesos físicos da obra não pode ultrapassar 100%');const valid=(await this.db.query<{id:string;displayOrder:number}>(client,`select id,display_order as "displayOrder" from app.stage_catalog where organization_id=$1 and id=any($2::uuid[]) and status='active'`,[context.organizationId,unique])).rows;if(valid.length!==unique.length)throw new BadRequestException('Uma ou mais etapas selecionadas não estão disponíveis');const existing=(await this.db.query<{catalogStageId:string}>(client,`select catalog_stage_id as "catalogStageId" from app.project_stages where organization_id=$1 and project_id=$2 and catalog_stage_id=any($3::uuid[])`,[context.organizationId,projectId,unique])).rows;if(existing.length)throw new BadRequestException('Uma ou mais etapas selecionadas já pertencem à obra');const supplier=(await this.db.query(client,`select id from app.suppliers where organization_id=$1 and id=$2 and status='active'`,[context.organizationId,input.primarySupplierId])).rows[0];if(!supplier)throw new BadRequestException('Fornecedor responsável não está disponível');const created=[];for(const item of valid.sort((a,b)=>a.displayOrder-b.displayOrder)){const stage=(await this.db.query<{id:string}>(client,`insert into app.project_stages(organization_id,project_id,catalog_stage_id,display_order,planned_start,planned_end,physical_weight,created_by,updated_by) values($1,$2,$3,$4,$5::date,$6::date,$7::numeric,$8,$8) returning id`,[context.organizationId,projectId,item.id,item.displayOrder,input.plannedStart,input.plannedEnd,weight,context.userId])).rows[0]!;await this.db.query(client,`insert into app.project_supplier_assignments(organization_id,project_id,project_stage_id,supplier_id,role_code,created_by) values($1,$2,$3,$4,'primary',$5)`,[context.organizationId,projectId,stage.id,input.primarySupplierId,context.userId]);created.push(stage);}return{count:created.length};});}

  removeStageStructure(context:TransactionContext,projectId:string,projectStageId:string){return this.db.withContext(context,async client=>{const root=(await this.db.query<{catalogStageId:string}>(client,`select catalog_stage_id as "catalogStageId" from app.project_stages where organization_id=$1 and project_id=$2 and id=$3`,[context.organizationId,projectId,projectStageId])).rows[0];if(!root)throw new BadRequestException('Etapa não encontrada na obra');const ids=(await this.db.query<{id:string}>(client,`with recursive catalog_tree as (select id from app.stage_catalog where organization_id=$1 and id=$3 union all select child.id from app.stage_catalog child join catalog_tree parent on child.parent_stage_id=parent.id where child.organization_id=$1) select ps.id from app.project_stages ps where ps.organization_id=$1 and ps.project_id=$2 and ps.catalog_stage_id in(select id from catalog_tree)`,[context.organizationId,projectId,root.catalogStageId])).rows.map(x=>x.id);await this.db.query(client,`delete from app.project_stage_dependencies where organization_id=$1 and project_id=$2 and (predecessor_stage_id=any($3::uuid[]) or successor_stage_id=any($3::uuid[]))`,[context.organizationId,projectId,ids]);await this.db.query(client,`delete from app.project_supplier_assignments where organization_id=$1 and project_id=$2 and (project_stage_id=any($3::uuid[]) or project_service_id in(select id from app.project_services where organization_id=$1 and project_id=$2 and project_stage_id=any($3::uuid[])))`,[context.organizationId,projectId,ids]);await this.db.query(client,`delete from app.project_services where organization_id=$1 and project_id=$2 and project_stage_id=any($3::uuid[])`,[context.organizationId,projectId,ids]);await this.db.query(client,`delete from app.project_stages where organization_id=$1 and project_id=$2 and id=any($3::uuid[])`,[context.organizationId,projectId,ids]);return{removed:ids.length};});}

  addStage(context: TransactionContext, projectId: string, input: AssignStageDto) {
    if (input.plannedEnd < input.plannedStart) throw new BadRequestException('Término deve ser posterior ao início');
    return this.db.withContext(context, async (client) => {
      const stage = (await this.db.query<{ id: string }>(client, `insert into app.project_stages(organization_id,project_id,catalog_stage_id,display_order,planned_start,planned_end,physical_weight,notes,created_by,updated_by) values($1,$2,$3,$4,$5::date,$6::date,$7::numeric,$8,$9,$9) returning id,catalog_stage_id as "catalogStageId",display_order as "displayOrder",planned_start as "plannedStart",planned_end as "plannedEnd",physical_weight as "physicalWeight",status,version`, [context.organizationId, projectId, input.catalogStageId, input.displayOrder, input.plannedStart, input.plannedEnd, input.physicalWeight, input.notes ?? null, context.userId])).rows[0];
      if (!stage) throw new Error('A etapa não foi criada');
      if (input.primarySupplierId) await this.db.query(client, `insert into app.project_supplier_assignments(organization_id,project_id,project_stage_id,supplier_id,role_code,created_by) values($1,$2,$3,$4,'primary',$5)`, [context.organizationId, projectId, stage.id, input.primarySupplierId, context.userId]);
      return stage;
    });
  }

  addService(context: TransactionContext, projectId: string, input: AssignServiceDto) {
    return this.db.withContext(context, async (client) => {
      // Serviço e fornecedor formam uma única unidade de negócio. Se a segunda
      // gravação falhar, `withContext` desfaz também o serviço e evita cadastro órfão.
      const service = (await this.db.query<{ id: string }>(client, `insert into app.project_services(organization_id,project_id,project_stage_id,catalog_service_id,environment_id,quantity,physical_weight,progress_criterion,created_by,updated_by) values($1,$2,$3,$4,$5,$6::numeric,$7::numeric,$8,$9,$9) returning id,project_stage_id as "projectStageId",catalog_service_id as "catalogServiceId",quantity,physical_weight as "physicalWeight",progress_criterion as "progressCriterion",status,version`, [context.organizationId, projectId, input.projectStageId, input.catalogServiceId, input.environmentId ?? null, input.quantity, input.physicalWeight, input.progressCriterion, context.userId])).rows[0];
      if (!service) throw new Error('O serviço não foi criado');
      await this.db.query(client, `insert into app.project_supplier_assignments(organization_id,project_id,project_service_id,supplier_id,role_code,created_by) values($1,$2,$3,$4,'primary',$5)`, [context.organizationId, projectId, service.id, input.supplierId, context.userId]);
      return service;
    });
  }

  addDependency(context: TransactionContext, projectId: string, input: CreateDependencyDto) {
    // A validação rápida melhora a mensagem; o banco repete a proteção e também
    // detecta ciclos indiretos para chamadas concorrentes ou outros clientes.
    if (input.predecessorStageId === input.successorStageId) throw new BadRequestException('Predecessor e sucessor devem ser diferentes');
    return this.db.withContext(context, async (client) => (await this.db.query(client, `insert into app.project_stage_dependencies(organization_id,project_id,predecessor_stage_id,successor_stage_id,dependency_type,lag_days,reason,created_by) values($1,$2,$3,$4,$5,$6,$7,$8) returning id,predecessor_stage_id as "predecessorStageId",successor_stage_id as "successorStageId",dependency_type as "dependencyType",lag_days as "lagDays",reason`, [context.organizationId, projectId, input.predecessorStageId, input.successorStageId, input.dependencyType, input.lagDays, input.reason ?? null, context.userId])).rows[0]);
  }
}
