import { Injectable, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { createHash, randomBytes } from 'node:crypto';
import * as argon2 from 'argon2';
import { DatabaseService } from '../database/database.service';
import { LoginDto } from './dto/login.dto';
import { AccessPayload } from './auth.types';

type LoginRow={id:string;name:string;email:string;status:string;passwordHash:string;failedAttempts:number;lockedUntil:Date|null;authVersion:string};
type Membership={organizationId:string;organizationName:string;roleCode:string};
type SessionRow={id:string;familyId:string;userId:string;organizationId:string;authVersion:string;expiresAt:Date;revokedAt:Date|null};

@Injectable()
export class AuthService {
  private dummyHash?:Promise<string>;
  constructor(private readonly db:DatabaseService,private readonly jwt:JwtService,private readonly config:ConfigService){}
  private hash(value:string){return createHash('sha256').update(value).digest();}
  private async fallbackHash(){return this.dummyHash??=argon2.hash('BOMzeika-dummy-password-never-valid',{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});}
  private async event(eventType:string,success:boolean,requestId:string|undefined,userId?:string,organizationId?:string,sessionId?:string,identifier?:string){await this.db.systemQuery(`insert into app.auth_events(user_id,organization_id,session_id,event_type,success,request_id,identifier_hash) values($1,$2,$3,$4,$5,$6,$7)`,[userId??null,organizationId??null,sessionId??null,eventType,success,requestId??null,identifier?this.hash(identifier):null]);}
  async login(input:LoginDto,requestId?:string){const email=input.email.trim().toLowerCase();const result=await this.db.systemQuery<LoginRow>(`select u.id,u.name,u.email,u.status,c.password_hash as "passwordHash",c.failed_attempts as "failedAttempts",c.locked_until as "lockedUntil",c.auth_version as "authVersion" from app.users u join app.user_credentials c on c.user_id=u.id where lower(trim(u.email))=$1`,[email]);const user=result.rows[0];const valid=await argon2.verify(user?.passwordHash??await this.fallbackHash(),input.password).catch(()=>false);if(!user||!valid||user.status!=='active'||(user.lockedUntil&&user.lockedUntil>new Date())){if(user){const attempts=user.failedAttempts+1;await this.db.systemQuery(`update app.user_credentials set failed_attempts=$2,locked_until=case when $2>=5 then clock_timestamp()+interval '15 minutes' else locked_until end,updated_at=clock_timestamp() where user_id=$1`,[user.id,attempts]);}await this.event('login_failure',false,requestId,user?.id,undefined,undefined,email);throw new UnauthorizedException('E-mail ou senha inválidos');}const memberships=(await this.db.systemQuery<Membership>(`select m.organization_id as "organizationId",o.trade_name as "organizationName",m.role_code as "roleCode" from app.organization_members m join app.organizations o on o.id=m.organization_id where m.user_id=$1 and m.status='active' and m.valid_from<=clock_timestamp() and (m.valid_to is null or m.valid_to>clock_timestamp()) and o.status='active' order by o.trade_name`,[user.id])).rows;const membership=input.organizationId?memberships.find(x=>x.organizationId===input.organizationId):memberships[0];if(!membership){await this.event('login_failure',false,requestId,user.id,undefined,undefined,email);throw new UnauthorizedException('E-mail ou senha inválidos');}await this.db.systemQuery(`update app.user_credentials set failed_attempts=0,locked_until=null,updated_at=clock_timestamp() where user_id=$1`,[user.id]);const issued=await this.createSession(user,membership,requestId);return{...issued,user:{id:user.id,name:user.name,email:user.email,role:membership.roleCode},organization:{id:membership.organizationId,name:membership.organizationName},memberships};}
  private async createSession(user:LoginRow,membership:Membership,requestId?:string){const refresh=randomBytes(32).toString('base64url'),csrf=randomBytes(24).toString('base64url'),expiresAt=new Date(Date.now()+30*86400000);const row=(await this.db.systemQuery<{id:string}>(`insert into app.auth_sessions(user_id,organization_id,refresh_token_hash,auth_version,expires_at) values($1,$2,$3,$4,$5) returning id`,[user.id,membership.organizationId,this.hash(refresh),Number(user.authVersion),expiresAt])).rows[0]!;const accessToken=await this.jwt.signAsync<AccessPayload>({sub:user.id,sid:row.id,organizationId:membership.organizationId,authVersion:Number(user.authVersion)},{secret:this.config.getOrThrow('jwt.secret'),issuer:this.config.getOrThrow('jwt.issuer'),audience:this.config.getOrThrow('jwt.audience'),expiresIn:'10m'});await this.event('login_success',true,requestId,user.id,membership.organizationId,row.id);return{accessToken,refreshToken:refresh,csrfToken:csrf,expiresIn:600};}
  async refresh(refreshToken:string,requestId?:string){const tokenHash=this.hash(refreshToken);const current=(await this.db.systemQuery<SessionRow&{name:string;email:string;roleCode:string;credentialVersion:string}>(`select s.id,s.family_id as "familyId",s.user_id as "userId",s.organization_id as "organizationId",s.auth_version as "authVersion",s.expires_at as "expiresAt",s.revoked_at as "revokedAt",u.name,u.email,m.role_code as "roleCode",c.auth_version as "credentialVersion" from app.auth_sessions s join app.users u on u.id=s.user_id join app.user_credentials c on c.user_id=u.id join app.organization_members m on m.user_id=s.user_id and m.organization_id=s.organization_id and m.status='active' where s.refresh_token_hash=$1 and s.revoked_at is null and s.expires_at>clock_timestamp() and u.status='active'`,[tokenHash])).rows[0];if(!current){const reused=(await this.db.systemQuery<{familyId:string}>(`select family_id as "familyId" from app.auth_sessions where previous_refresh_hash=$1`,[tokenHash])).rows[0];if(reused)await this.db.systemQuery(`update app.auth_sessions set revoked_at=clock_timestamp(),revoke_reason='refresh_reuse' where family_id=$1 and revoked_at is null`,[reused.familyId]);throw new UnauthorizedException('Sessão inválida ou expirada');}if(Number(current.authVersion)!==Number(current.credentialVersion))throw new UnauthorizedException('Sessão inválida ou expirada');const next=randomBytes(32).toString('base64url'),csrf=randomBytes(24).toString('base64url');await this.db.systemQuery(`update app.auth_sessions set previous_refresh_hash=refresh_token_hash,refresh_token_hash=$2,last_used_at=clock_timestamp() where id=$1`,[current.id,this.hash(next)]);const accessToken=await this.jwt.signAsync<AccessPayload>({sub:current.userId,sid:current.id,organizationId:current.organizationId,authVersion:Number(current.authVersion)},{secret:this.config.getOrThrow('jwt.secret'),issuer:this.config.getOrThrow('jwt.issuer'),audience:this.config.getOrThrow('jwt.audience'),expiresIn:'10m'});await this.event('refresh',true,requestId,current.userId,current.organizationId,current.id);return{accessToken,refreshToken:next,csrfToken:csrf,expiresIn:600};}
  async me(userId:string,organizationId:string){const row=(await this.db.systemQuery<{id:string;name:string;email:string;role:string;organizationName:string}>(`select u.id,u.name,u.email,m.role_code as role,o.trade_name as "organizationName" from app.users u join app.organization_members m on m.user_id=u.id and m.organization_id=$2 and m.status='active' join app.organizations o on o.id=m.organization_id where u.id=$1 and u.status='active'`,[userId,organizationId])).rows[0];if(!row)throw new UnauthorizedException('Sessão inválida');return{user:{id:row.id,name:row.name,email:row.email,role:row.role},organization:{id:organizationId,name:row.organizationName}};}
  async logout(sessionId:string,userId:string,organizationId:string,requestId?:string){await this.db.systemQuery(`update app.auth_sessions set revoked_at=coalesce(revoked_at,clock_timestamp()),revoke_reason=coalesce(revoke_reason,'logout') where id=$1 and user_id=$2`,[sessionId,userId]);await this.event('logout',true,requestId,userId,organizationId,sessionId);}
  async validateSession(payload:AccessPayload){return(await this.db.systemQuery<{roleCode:string}>(`select m.role_code as "roleCode" from app.auth_sessions s join app.users u on u.id=s.user_id and u.status='active' join app.user_credentials c on c.user_id=u.id and c.auth_version=s.auth_version join app.organization_members m on m.user_id=s.user_id and m.organization_id=s.organization_id and m.status='active' where s.id=$1 and s.user_id=$2 and s.organization_id=$3 and s.revoked_at is null and s.expires_at>clock_timestamp()`,[payload.sid,payload.sub,payload.organizationId])).rows[0];}
}
